# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bac9a13b2560b8e402c366df78e1659f623681e56d9e1aef13774cbf20f2773649ba74defbb3d6ec69294b5257ad31c8945e6bd8c5b7fd1f93e5743d94db4538

test:
  secret_key_base: 617f2dfbbd00c874e4f9dfa75e52986020688d9262bdfe1dfb3b23c9d527a82e78d281a74133a50a7df89278cfbb6612c84fd8864df4865afc5d494fb0561fef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
